language: ruby

rvm:
  - "2.3.1"

services:
  - mysql

before_script:
 - sudo apt-get install libmysqlclient-dev  
 - gem install rspec rspec-rails simplecov codeclimate-test-reporter
 - bundle install

script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS `observatorio-producaoTest` CHARACTER SET utf8 COLLATE utf8_general_ci'
  - mysql observatorio-producaoTest < db/observatorio_producao.sql -uroot
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec

after_success:
  - CODECLIMATE_REPO_TOKEN=2295d3595bea327ad6b16da50000e97765864033786a392b568eadfceea62476 bundle exec rake 

notifications:
  email:
    recipients:
      - lhqmalta@gmail.com
      - andrade.icaa@gmail.com

